platform :ios,'6.1'
pod 'ASIHTTPRequest', '~> 1.8.1'
pod 'OCMapper', '~> 1.0.1'
pod 'EGOImageLoading', '~> 0.0.1'
pod 'EGOCache', '~> 2.0'
pod 'EGOTableViewPullRefresh',:git => 'https://github.com/aiyuelian/EGOTableViewPullRefresh'
